### ISSUE TITLE
Update process mappings with new driver key value

### ISSUE THREAD

**Issue by rc-abodkins** [redcanaryco/surveyor#65]
**Which category is the feature part of?**
- [x] Carbon Black Response
- [x] Threat Hunter
- [ ] Definition File
- [ ] Code Feature - impacts all products 
- [ ] New product support
- [x] S1
- [x] MDE
 
**Use Cases**
With the new definition file regarding vulnerable drivers we have to add the key for `hash` to the process mapping for how each EDR calls the hashes. 
 
**Proposal**

**Additional context**

**Comment by rc-abodkins** [comment]
#61

**Comment by xC0uNt3r7hr34t** [comment]
The other option we talked about would be to implement the ability to specify a hash and let each product file determine how to use it. this could also be potentially done within the surveyor.py logic where we use something like https://pypi.org/project/hashID/. 

Carbon Black has the trickiest fields for this while S1 and MDE each have more general hash fields.
- MD5
- SHA1
- SHA256

regardless of whether we automatically determine hash type or require users to define it in arguments or definition files, it would be best to pass all hashes to the product file and simply let them discard any that are not supported by that product as is done today with the parameter mapping.

**Comment by rc-csmith** [comment]
Thanks for keeping me honest! I remember now we _did_ decide to lump all hash types into a single key. 

One thing to consider is making sure that when we build the parameter mappings, the code supports any occurrence of the hash - be it for process execution, file write, or module load. Otherwise, we'd have to have three separate keys like `process_hash`, `filewrite_hash`, `modload_hash`.

**Comment by TreWilkinsRC** [comment]
Covered by sigma support, closing!
